debug: true

logging:
  level:
    tomcat: "debug"
    web: "trace"
    config: "trace"


spring:
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    in-memory:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:testdb
      name: inMemory-pool
      username: sa
      password:


management:
  endpoints:
    web:
      exposure:
        include: "*"


envprop.apbase:
  common:
    in-memory.enable: true

---

spring:
  config:
    activate:
      on-profile: 
      - b2b
      - b2c
      
  datasource:
    in-memory:
      schema:
      - classpath:/org/springframework/session/jdbc/schema-h2.sql
      
---

spring:
  config:
    activate:
      on-profile: 
      - syncbatch
      - asyncbatch
      
  datasource:
    in-memory:
      schema:
      - classpath:/org/springframework/batch/core/schema-h2.sql
