debug: true

logging:
  level:
    tomcat: "debug"
    web: "trace"
    apbase: "trace"
    share: "trace"
    front: "trace"
    back: "trace"
    batch: "trace"
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error

spring:
  h2:
    console:
      enabled: true
      path: /h2
      

management:
  endpoints:
    web:
      exposure:
        include: "*"


server:
  error:
    include-exception: true
    include-binding-errors: always
    include-message: always
    include-stacktrace: always

cloud:
  aws:
    credentials:
      instance-profile: false
    stack:      auto: false
    region:      auto: false
      static: ap-northeast-1
#    endpoint: http://localhost:4566
    
    

---

spring:
  config:
    activate:
      on-profile: 
      - b2b
server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: 
      - b2c
server:
  port: 8081
  
---

spring:
  config:
    activate:
      on-profile: 
      - syncbatch
      - asyncbatch
    
